### ISSUE TITLE
How to download a file from hydro ?

### ISSUE THREAD

**Issue by Tva540** [hydrostack/hydro#108]
Hi, I'm encountering an issue with file downloads while using Hydro component. The goal is to download a file via JavaScript, as shown below:
```
function saveAsFile(filename, bytesBase64) {
    var link = document.createElement('a');
    link.download = filename;
    link.href = "data:application/octet-stream;base64," + bytesBase64;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
}
```
here's the c# code 
` Client.ExecuteJs($"saveAsFile('{fileName}','{base64Excel}')");`

The approach works in some cases, but it becomes unreliable, especially when the file size is large. When attempting to download a large file, the download fails, and I receive either of the following error in the console:
`POST https://localhost:7064/hydro/ListReport/DownloadReport net::ERR_CONNECTION_RESET`
`POST https://localhost:7064/hydro/ListReport/DownloadReport net::ERR_HTTP2_PROTOCOL_ERROR`

**Comment by Tva540** [comment]
> Client.ExecuteJs statements go into response headers, which contains a size limit, so probably that's why it fails. You're trying to return a file from an action, is that correct?

Yes correct, I'm trying to return a file from an action, may I know what is the proper way to do it, Thanks.

**Comment by kjeske** [comment]
Soon I will release a new version in which you will return a file from your method. But for now you can use a simple workaround:

Create a new property in your component:

```c#
[Transient]
public string FileData { get; set; }
```

Modify your download action to populate this field with Base64 content and to pass additional argument to your function:

```c#
public void Download()
{
    FileData = ; // your base64 content goes here
    Client.ExecuteJs("saveAsFile(this.querySelector('[data-file]'), 'file.txt')");
}
```

Add `data-file` attribute to your button or other element:

```razor
<button type="button" hydro-on:click="@(() => Model.Download())" data-file="@Model.FileData">
  Download
</button>
```

Modify your `saveAs` function:

```js
function saveAsFile(el, filename) {
  var bytesBase64 = el.getAttribute('data-file'); // here we are getting the base64 content
  var link = document.createElement('a');
  link.download = filename;
  link.href = "data:application/octet-stream;base64," + bytesBase64;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}
```

This is just a workaround, in a few days there will be a new release with a proper solution.

**Comment by Tva540** [comment]
Thanks for the workaround @kjeske, i have tested and it works perfectly, waiting for the next hydro release. ✌️

**Comment by kjeske** [comment]
Didn't make it for v1.0 release, but will be a part of the next minor.

**Comment by kjeske** [comment]
Moved to #90
