### ISSUE TITLE
How to package a button and more  as a component ?

### ISSUE THREAD

**Issue by hanxiao123** [hydrostack/hydro#112]
To package a button and more as a component and pass events through an Action, ultimately achieving something like <mybutton click="@(()=>Model.Upload())" type="primary" icon="file">Upload</mybutton>

**Comment by hanxiao123** [comment]
hydroview implements slots,but can't pass event.

**Comment by kjeske** [comment]
Have you tried the following?

```c#
public class FormButton : HydroView
{
    public Expression Click { get; set; }
}
```

```razor
@model FormButton

<button on:click="@Model.Click">
  @Model.Slot()
</button>
```

Usage:

```razor
<form-button click="@(() => Model.Save())">
  Save
</form-button>
```

More examples here:
https://toolkit.usehydro.dev/examples/actions/

**Comment by hanxiao123** [comment]
Thank you! It's perfect!
