### ISSUE TITLE
Component not updating although the DOM upon the return of a response

### ISSUE THREAD

**Issue by NejcBW** [hydrostack/hydro#14]
Hello,

I have encountered an issue for which I don't know if it's a bug or my miscomprehension of the Hydro's concept.

To illustrate the situation, I will use a simple component that displays a list of items:

```razor
<div>
    <ul>
        @foreach (var item in Model.Items)
        {
            <li>@item</li>
        }
        
        <button type="button" hydro-on:click="@(()=>Model.Remove())">Remove first</button>
    </ul>
</div>
```

Then in the model there is a property containing a list of items and a method that removes the first element of the list.

```csharp
public List<string> Items { get; set; } 

public override void Mount()
{
    Items = ["Item 1", "Item 2", "Item 3"];
}

public void Remove()
{
    Items.RemoveAt(0);
}
```

When the button is clicked and the Remove method is triggered, I would expect the component to be swapped in the DOM. However, this does not happen although the response contains a new `<ul>` holding just the Item 2 and Item 3 `<li>` elements.

Thanks a lot!
Nejc

**Comment by kjeske** [comment]
Hi Nejc!
I've just checked your component and it worked for me. I clicked the button and the first item got removed. Did you follow all the instructions from the [Getting started](https://usehydro.dev/introduction/getting-started.html)?

Krzysztof

**Comment by NejcBW** [comment]
Cześć,

My bad, I had my own Alpine.js script and no Morph plugin!

Bardzo bardzo Ci dziękuję za odpowiedź!

Nejc

**Comment by kjeske** [comment]
Hej, nie ma problemu :)
KJ
