### ISSUE TITLE
Navigation initiated in components to "/" results in error

### ISSUE THREAD

**Issue by westonwalker** [hydrostack/hydro#3]
Hi there,

I have a form that on submit, saves some data and then redirects (without page reload) the user to the home page "/".

```
public void Submit()
{
  if (!Validate())
  {
    return;
  }
  
  var newContact = new Contact();
  newContact.Name = Name;
  newContact.Email = Email;
  Database.Contacts.Add(newContact);

  Location(Url.Page("/"));
}
```

The location change results in an error. It looks like when passing "" or "/" to the Url.Page method, the resulting path is null. Network request below showing "path": null. This works fine when passing urls that aren't the home page.
![image](https://github.com/hydrostack/hydro/assets/66449990/61a11890-0e65-461e-8695-eb2008546012)

**Comment by kjeske** [comment]
Hi! The `pageName` parameter expects a valid Razor Page name, so it will be either "/Index" or "/Home/Index" or similar depending on your folder structure.

It seems it would be good in Hydro to check the path that is passed to `Location`, and if it's null or empty throw appropriate exception. Will fix.

**Comment by westonwalker** [comment]
Thanks for the quick reply. Really enjoyed using the library yesterday!
