### ISSUE TITLE
hydro-link navigation does not reset scroll position on new page

### ISSUE THREAD

**Issue by westonwalker** [hydrostack/hydro#9]
When navigating to a new page with hydro-link, the scroll position remains the same as it was on the previous page, requiring the user to scroll back up to the top of the page.

A better UX would be resetting the scroll position to the top of the new page.

Attached video example of issue.

https://github.com/hydrostack/hydro/assets/66449990/a791267e-d919-4bc1-bb37-a5d8bdb2b980

**Comment by kjeske** [comment]
Thanks for the video example! It's now fixed in v0.8.5.
